version: '3'

services:
  apache:
    image: httpd:2.4
    volumes:
      - ./public_html:/var/www/html
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php
  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./public_html:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - apache
  php:
    build:
        context: ./
        dockerfile: docker/php-fpm.docker    
    volumes:
      - ./public_html:/var/www/html
